services:
  db_canetex:
    image: postgres:14-alpine
    container_name: canetex_db
    volumes:
      - canetex_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: indio2272
    restart: always

  web:
    image: windsney/canetex:latest
    container_name: canetex_app
    ports:
      - "8001:8000"
    environment:
      SECRET_KEY: 'django-insecure-1pi2z^&y%qo-q9&z$znjxk98)5z2rvb)&z*jawt#21yv9q9&-1'
      DEBUG: 'False'
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: indio2272
      DB_HOST: db_canetex  # <--- AGORA COMBINA COM O NOME ACIMA
      DB_PORT: 5432
    depends_on:
      - db_canetex          # <--- AGORA COMBINA COM O NOME ACIMA
    restart: always

volumes:
  canetex_postgres_data:    # <--- AGORA COMBINA COM O NOME NO SERVIÇO:
